package com.ciotc.teemo.domain;

public class Movies {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.patientid
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String patientid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.createtime
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String createtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.path
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String path;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.description
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.linkphoto
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String linkphoto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movies.comments
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String comments;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.id
	 * @return  the value of movies.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.id
	 * @param id  the value for movies.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.patientid
	 * @return  the value of movies.patientid
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getPatientid() {
		return patientid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.patientid
	 * @param patientid  the value for movies.patientid
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setPatientid(String patientid) {
		this.patientid = patientid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.createtime
	 * @return  the value of movies.createtime
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.createtime
	 * @param createtime  the value for movies.createtime
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.path
	 * @return  the value of movies.path
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.path
	 * @param path  the value for movies.path
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.description
	 * @return  the value of movies.description
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.description
	 * @param description  the value for movies.description
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.linkphoto
	 * @return  the value of movies.linkphoto
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getLinkphoto() {
		return linkphoto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.linkphoto
	 * @param linkphoto  the value for movies.linkphoto
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setLinkphoto(String linkphoto) {
		this.linkphoto = linkphoto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movies.comments
	 * @return  the value of movies.comments
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movies.comments
	 * @param comments  the value for movies.comments
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}
}