package com.ciotc.teemo.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MoviesExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public MoviesExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected MoviesExample(MoviesExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public static class Criteria {
	protected List criteriaWithoutValue;
	protected List criteriaWithSingleValue;
	protected List criteriaWithListValue;
	protected List criteriaWithBetweenValue;
	
	protected Criteria() {
		super();
		criteriaWithoutValue = new ArrayList();
		criteriaWithSingleValue = new ArrayList();
		criteriaWithListValue = new ArrayList();
		criteriaWithBetweenValue = new ArrayList();
	}
	
	public boolean isValid() {
		return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
				|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
	}
	
	public List getCriteriaWithoutValue() {
		return criteriaWithoutValue;
	}
	
	public List getCriteriaWithSingleValue() {
		return criteriaWithSingleValue;
	}
	
	public List getCriteriaWithListValue() {
		return criteriaWithListValue;
	}
	
	public List getCriteriaWithBetweenValue() {
		return criteriaWithBetweenValue;
	}
	
	protected void addCriterion(String condition) {
		if (condition == null) {
			throw new RuntimeException("Value for condition cannot be null");
		}
		criteriaWithoutValue.add(condition);
	}
	
	protected void addCriterion(String condition, Object value, String property) {
		if (value == null) {
			throw new RuntimeException("Value for " + property + " cannot be null");
		}
		Map map = new HashMap();
		map.put("condition", condition);
		map.put("value", value);
		criteriaWithSingleValue.add(map);
	}
	
	protected void addCriterion(String condition, List values, String property) {
		if (values == null || values.size() == 0) {
			throw new RuntimeException("Value list for " + property + " cannot be null or empty");
		}
		Map map = new HashMap();
		map.put("condition", condition);
		map.put("values", values);
		criteriaWithListValue.add(map);
	}
	
	protected void addCriterion(String condition, Object value1, Object value2, String property) {
		if (value1 == null || value2 == null) {
			throw new RuntimeException("Between values for " + property + " cannot be null");
		}
		List list = new ArrayList();
		list.add(value1);
		list.add(value2);
		Map map = new HashMap();
		map.put("condition", condition);
		map.put("values", list);
		criteriaWithBetweenValue.add(map);
	}
	
	public Criteria andIdIsNull() {
		addCriterion("id is null");
		return this;
	}
	
	public Criteria andIdIsNotNull() {
		addCriterion("id is not null");
		return this;
	}
	
	public Criteria andIdEqualTo(String value) {
		addCriterion("id =", value, "id");
		return this;
	}
	
	public Criteria andIdNotEqualTo(String value) {
		addCriterion("id <>", value, "id");
		return this;
	}
	
	public Criteria andIdGreaterThan(String value) {
		addCriterion("id >", value, "id");
		return this;
	}
	
	public Criteria andIdGreaterThanOrEqualTo(String value) {
		addCriterion("id >=", value, "id");
		return this;
	}
	
	public Criteria andIdLessThan(String value) {
		addCriterion("id <", value, "id");
		return this;
	}
	
	public Criteria andIdLessThanOrEqualTo(String value) {
		addCriterion("id <=", value, "id");
		return this;
	}
	
	public Criteria andIdLike(String value) {
		addCriterion("id like", value, "id");
		return this;
	}
	
	public Criteria andIdNotLike(String value) {
		addCriterion("id not like", value, "id");
		return this;
	}
	
	public Criteria andIdIn(List values) {
		addCriterion("id in", values, "id");
		return this;
	}
	
	public Criteria andIdNotIn(List values) {
		addCriterion("id not in", values, "id");
		return this;
	}
	
	public Criteria andIdBetween(String value1, String value2) {
		addCriterion("id between", value1, value2, "id");
		return this;
	}
	
	public Criteria andIdNotBetween(String value1, String value2) {
		addCriterion("id not between", value1, value2, "id");
		return this;
	}
	
	public Criteria andPatientidIsNull() {
		addCriterion("patientid is null");
		return this;
	}
	
	public Criteria andPatientidIsNotNull() {
		addCriterion("patientid is not null");
		return this;
	}
	
	public Criteria andPatientidEqualTo(String value) {
		addCriterion("patientid =", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidNotEqualTo(String value) {
		addCriterion("patientid <>", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidGreaterThan(String value) {
		addCriterion("patientid >", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidGreaterThanOrEqualTo(String value) {
		addCriterion("patientid >=", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidLessThan(String value) {
		addCriterion("patientid <", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidLessThanOrEqualTo(String value) {
		addCriterion("patientid <=", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidLike(String value) {
		addCriterion("patientid like", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidNotLike(String value) {
		addCriterion("patientid not like", value, "patientid");
		return this;
	}
	
	public Criteria andPatientidIn(List values) {
		addCriterion("patientid in", values, "patientid");
		return this;
	}
	
	public Criteria andPatientidNotIn(List values) {
		addCriterion("patientid not in", values, "patientid");
		return this;
	}
	
	public Criteria andPatientidBetween(String value1, String value2) {
		addCriterion("patientid between", value1, value2, "patientid");
		return this;
	}
	
	public Criteria andPatientidNotBetween(String value1, String value2) {
		addCriterion("patientid not between", value1, value2, "patientid");
		return this;
	}
	
	public Criteria andCreatetimeIsNull() {
		addCriterion("createtime is null");
		return this;
	}
	
	public Criteria andCreatetimeIsNotNull() {
		addCriterion("createtime is not null");
		return this;
	}
	
	public Criteria andCreatetimeEqualTo(String value) {
		addCriterion("createtime =", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotEqualTo(String value) {
		addCriterion("createtime <>", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeGreaterThan(String value) {
		addCriterion("createtime >", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
		addCriterion("createtime >=", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeLessThan(String value) {
		addCriterion("createtime <", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeLessThanOrEqualTo(String value) {
		addCriterion("createtime <=", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeLike(String value) {
		addCriterion("createtime like", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotLike(String value) {
		addCriterion("createtime not like", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeIn(List values) {
		addCriterion("createtime in", values, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotIn(List values) {
		addCriterion("createtime not in", values, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeBetween(String value1, String value2) {
		addCriterion("createtime between", value1, value2, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotBetween(String value1, String value2) {
		addCriterion("createtime not between", value1, value2, "createtime");
		return this;
	}
	
	public Criteria andPathIsNull() {
		addCriterion("path is null");
		return this;
	}
	
	public Criteria andPathIsNotNull() {
		addCriterion("path is not null");
		return this;
	}
	
	public Criteria andPathEqualTo(String value) {
		addCriterion("path =", value, "path");
		return this;
	}
	
	public Criteria andPathNotEqualTo(String value) {
		addCriterion("path <>", value, "path");
		return this;
	}
	
	public Criteria andPathGreaterThan(String value) {
		addCriterion("path >", value, "path");
		return this;
	}
	
	public Criteria andPathGreaterThanOrEqualTo(String value) {
		addCriterion("path >=", value, "path");
		return this;
	}
	
	public Criteria andPathLessThan(String value) {
		addCriterion("path <", value, "path");
		return this;
	}
	
	public Criteria andPathLessThanOrEqualTo(String value) {
		addCriterion("path <=", value, "path");
		return this;
	}
	
	public Criteria andPathLike(String value) {
		addCriterion("path like", value, "path");
		return this;
	}
	
	public Criteria andPathNotLike(String value) {
		addCriterion("path not like", value, "path");
		return this;
	}
	
	public Criteria andPathIn(List values) {
		addCriterion("path in", values, "path");
		return this;
	}
	
	public Criteria andPathNotIn(List values) {
		addCriterion("path not in", values, "path");
		return this;
	}
	
	public Criteria andPathBetween(String value1, String value2) {
		addCriterion("path between", value1, value2, "path");
		return this;
	}
	
	public Criteria andPathNotBetween(String value1, String value2) {
		addCriterion("path not between", value1, value2, "path");
		return this;
	}
	
	public Criteria andDescriptionIsNull() {
		addCriterion("description is null");
		return this;
	}
	
	public Criteria andDescriptionIsNotNull() {
		addCriterion("description is not null");
		return this;
	}
	
	public Criteria andDescriptionEqualTo(String value) {
		addCriterion("description =", value, "description");
		return this;
	}
	
	public Criteria andDescriptionNotEqualTo(String value) {
		addCriterion("description <>", value, "description");
		return this;
	}
	
	public Criteria andDescriptionGreaterThan(String value) {
		addCriterion("description >", value, "description");
		return this;
	}
	
	public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
		addCriterion("description >=", value, "description");
		return this;
	}
	
	public Criteria andDescriptionLessThan(String value) {
		addCriterion("description <", value, "description");
		return this;
	}
	
	public Criteria andDescriptionLessThanOrEqualTo(String value) {
		addCriterion("description <=", value, "description");
		return this;
	}
	
	public Criteria andDescriptionLike(String value) {
		addCriterion("description like", value, "description");
		return this;
	}
	
	public Criteria andDescriptionNotLike(String value) {
		addCriterion("description not like", value, "description");
		return this;
	}
	
	public Criteria andDescriptionIn(List values) {
		addCriterion("description in", values, "description");
		return this;
	}
	
	public Criteria andDescriptionNotIn(List values) {
		addCriterion("description not in", values, "description");
		return this;
	}
	
	public Criteria andDescriptionBetween(String value1, String value2) {
		addCriterion("description between", value1, value2, "description");
		return this;
	}
	
	public Criteria andDescriptionNotBetween(String value1, String value2) {
		addCriterion("description not between", value1, value2, "description");
		return this;
	}
	
	public Criteria andLinkphotoIsNull() {
		addCriterion("linkphoto is null");
		return this;
	}
	
	public Criteria andLinkphotoIsNotNull() {
		addCriterion("linkphoto is not null");
		return this;
	}
	
	public Criteria andLinkphotoEqualTo(String value) {
		addCriterion("linkphoto =", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoNotEqualTo(String value) {
		addCriterion("linkphoto <>", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoGreaterThan(String value) {
		addCriterion("linkphoto >", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoGreaterThanOrEqualTo(String value) {
		addCriterion("linkphoto >=", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoLessThan(String value) {
		addCriterion("linkphoto <", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoLessThanOrEqualTo(String value) {
		addCriterion("linkphoto <=", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoLike(String value) {
		addCriterion("linkphoto like", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoNotLike(String value) {
		addCriterion("linkphoto not like", value, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoIn(List values) {
		addCriterion("linkphoto in", values, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoNotIn(List values) {
		addCriterion("linkphoto not in", values, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoBetween(String value1, String value2) {
		addCriterion("linkphoto between", value1, value2, "linkphoto");
		return this;
	}
	
	public Criteria andLinkphotoNotBetween(String value1, String value2) {
		addCriterion("linkphoto not between", value1, value2, "linkphoto");
		return this;
	}
	
	public Criteria andCommentsIsNull() {
		addCriterion("comments is null");
		return this;
	}
	
	public Criteria andCommentsIsNotNull() {
		addCriterion("comments is not null");
		return this;
	}
	
	public Criteria andCommentsEqualTo(String value) {
		addCriterion("comments =", value, "comments");
		return this;
	}
	
	public Criteria andCommentsNotEqualTo(String value) {
		addCriterion("comments <>", value, "comments");
		return this;
	}
	
	public Criteria andCommentsGreaterThan(String value) {
		addCriterion("comments >", value, "comments");
		return this;
	}
	
	public Criteria andCommentsGreaterThanOrEqualTo(String value) {
		addCriterion("comments >=", value, "comments");
		return this;
	}
	
	public Criteria andCommentsLessThan(String value) {
		addCriterion("comments <", value, "comments");
		return this;
	}
	
	public Criteria andCommentsLessThanOrEqualTo(String value) {
		addCriterion("comments <=", value, "comments");
		return this;
	}
	
	public Criteria andCommentsLike(String value) {
		addCriterion("comments like", value, "comments");
		return this;
	}
	
	public Criteria andCommentsNotLike(String value) {
		addCriterion("comments not like", value, "comments");
		return this;
	}
	
	public Criteria andCommentsIn(List values) {
		addCriterion("comments in", values, "comments");
		return this;
	}
	
	public Criteria andCommentsNotIn(List values) {
		addCriterion("comments not in", values, "comments");
		return this;
	}
	
	public Criteria andCommentsBetween(String value1, String value2) {
		addCriterion("comments between", value1, value2, "comments");
		return this;
	}
	
	public Criteria andCommentsNotBetween(String value1, String value2) {
		addCriterion("comments not between", value1, value2, "comments");
		return this;
	}
	}
}