package com.ciotc.teemo.domain;

public class Patients {
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.name
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.idcard
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String idcard;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.age
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private int age;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.gender
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private int gender;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.arch
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private float arch;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.createtime
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String createtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.birth
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String birth;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.powerA
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String powera;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column patients.gain
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String gain;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.id
	 * @return  the value of patients.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.id
	 * @param id  the value for patients.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.name
	 * @return  the value of patients.name
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.name
	 * @param name  the value for patients.name
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.idcard
	 * @return  the value of patients.idcard
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.idcard
	 * @param idcard  the value for patients.idcard
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.age
	 * @return  the value of patients.age
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int getAge() {
		return age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.age
	 * @param age  the value for patients.age
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setAge(int age) {
		this.age = age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.gender
	 * @return  the value of patients.gender
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int getGender() {
		return gender;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.gender
	 * @param pGender  the value for patients.gender
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setGender(int pGender) {
		this.gender = pGender;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.arch
	 * @return  the value of patients.arch
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public float getArch() {
		return arch;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.arch
	 * @param pArch  the value for patients.arch
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setArch(float pArch) {
		this.arch = pArch;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.createtime
	 * @return  the value of patients.createtime
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.createtime
	 * @param createtime  the value for patients.createtime
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.birth
	 * @return  the value of patients.birth
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getBirth() {
		return birth;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.birth
	 * @param birth  the value for patients.birth
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setBirth(String birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.powerA
	 * @return  the value of patients.powerA
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getPowerA() {
		return powera;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.powerA
	 * @param powera  the value for patients.powerA
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setPowerA(String powera) {
		this.powera = powera;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column patients.gain
	 * @return  the value of patients.gain
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getGain() {
		return gain;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column patients.gain
	 * @param gain  the value for patients.gain
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setGain(String gain) {
		this.gain = gain;
	}

	public String toString(){
		return name;
    	
    }
}