package com.ciotc.teemo.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PatientsExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public PatientsExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected PatientsExample(PatientsExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table patients
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public static class Criteria {
	protected List criteriaWithoutValue;
	protected List criteriaWithSingleValue;
	protected List criteriaWithListValue;
	protected List criteriaWithBetweenValue;
	
	protected Criteria() {
		super();
		criteriaWithoutValue = new ArrayList();
		criteriaWithSingleValue = new ArrayList();
		criteriaWithListValue = new ArrayList();
		criteriaWithBetweenValue = new ArrayList();
	}
	
	public boolean isValid() {
		return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
				|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
	}
	
	public List getCriteriaWithoutValue() {
		return criteriaWithoutValue;
	}
	
	public List getCriteriaWithSingleValue() {
		return criteriaWithSingleValue;
	}
	
	public List getCriteriaWithListValue() {
		return criteriaWithListValue;
	}
	
	public List getCriteriaWithBetweenValue() {
		return criteriaWithBetweenValue;
	}
	
	protected void addCriterion(String condition) {
		if (condition == null) {
			throw new RuntimeException("Value for condition cannot be null");
		}
		criteriaWithoutValue.add(condition);
	}
	
	protected void addCriterion(String condition, Object value, String property) {
		if (value == null) {
			throw new RuntimeException("Value for " + property + " cannot be null");
		}
		Map map = new HashMap();
		map.put("condition", condition);
		map.put("value", value);
		criteriaWithSingleValue.add(map);
	}
	
	protected void addCriterion(String condition, List values, String property) {
		if (values == null || values.size() == 0) {
			throw new RuntimeException("Value list for " + property + " cannot be null or empty");
		}
		Map map = new HashMap();
		map.put("condition", condition);
		map.put("values", values);
		criteriaWithListValue.add(map);
	}
	
	protected void addCriterion(String condition, Object value1, Object value2, String property) {
		if (value1 == null || value2 == null) {
			throw new RuntimeException("Between values for " + property + " cannot be null");
		}
		List list = new ArrayList();
		list.add(value1);
		list.add(value2);
		Map map = new HashMap();
		map.put("condition", condition);
		map.put("values", list);
		criteriaWithBetweenValue.add(map);
	}
	
	public Criteria andIdIsNull() {
		addCriterion("id is null");
		return this;
	}
	
	public Criteria andIdIsNotNull() {
		addCriterion("id is not null");
		return this;
	}
	
	public Criteria andIdEqualTo(String value) {
		addCriterion("id =", value, "id");
		return this;
	}
	
	public Criteria andIdNotEqualTo(String value) {
		addCriterion("id <>", value, "id");
		return this;
	}
	
	public Criteria andIdGreaterThan(String value) {
		addCriterion("id >", value, "id");
		return this;
	}
	
	public Criteria andIdGreaterThanOrEqualTo(String value) {
		addCriterion("id >=", value, "id");
		return this;
	}
	
	public Criteria andIdLessThan(String value) {
		addCriterion("id <", value, "id");
		return this;
	}
	
	public Criteria andIdLessThanOrEqualTo(String value) {
		addCriterion("id <=", value, "id");
		return this;
	}
	
	public Criteria andIdLike(String value) {
		addCriterion("id like", value, "id");
		return this;
	}
	
	public Criteria andIdNotLike(String value) {
		addCriterion("id not like", value, "id");
		return this;
	}
	
	public Criteria andIdIn(List values) {
		addCriterion("id in", values, "id");
		return this;
	}
	
	public Criteria andIdNotIn(List values) {
		addCriterion("id not in", values, "id");
		return this;
	}
	
	public Criteria andIdBetween(String value1, String value2) {
		addCriterion("id between", value1, value2, "id");
		return this;
	}
	
	public Criteria andIdNotBetween(String value1, String value2) {
		addCriterion("id not between", value1, value2, "id");
		return this;
	}
	
	public Criteria andNameIsNull() {
		addCriterion("name is null");
		return this;
	}
	
	public Criteria andNameIsNotNull() {
		addCriterion("name is not null");
		return this;
	}
	
	public Criteria andNameEqualTo(String value) {
		addCriterion("name =", value, "name");
		return this;
	}
	
	public Criteria andNameNotEqualTo(String value) {
		addCriterion("name <>", value, "name");
		return this;
	}
	
	public Criteria andNameGreaterThan(String value) {
		addCriterion("name >", value, "name");
		return this;
	}
	
	public Criteria andNameGreaterThanOrEqualTo(String value) {
		addCriterion("name >=", value, "name");
		return this;
	}
	
	public Criteria andNameLessThan(String value) {
		addCriterion("name <", value, "name");
		return this;
	}
	
	public Criteria andNameLessThanOrEqualTo(String value) {
		addCriterion("name <=", value, "name");
		return this;
	}
	
	public Criteria andNameLike(String value) {
		addCriterion("name like", value, "name");
		return this;
	}
	
	public Criteria andNameNotLike(String value) {
		addCriterion("name not like", value, "name");
		return this;
	}
	
	public Criteria andNameIn(List values) {
		addCriterion("name in", values, "name");
		return this;
	}
	
	public Criteria andNameNotIn(List values) {
		addCriterion("name not in", values, "name");
		return this;
	}
	
	public Criteria andNameBetween(String value1, String value2) {
		addCriterion("name between", value1, value2, "name");
		return this;
	}
	
	public Criteria andNameNotBetween(String value1, String value2) {
		addCriterion("name not between", value1, value2, "name");
		return this;
	}
	
	public Criteria andIdcardIsNull() {
		addCriterion("idcard is null");
		return this;
	}
	
	public Criteria andIdcardIsNotNull() {
		addCriterion("idcard is not null");
		return this;
	}
	
	public Criteria andIdcardEqualTo(String value) {
		addCriterion("idcard =", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardNotEqualTo(String value) {
		addCriterion("idcard <>", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardGreaterThan(String value) {
		addCriterion("idcard >", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardGreaterThanOrEqualTo(String value) {
		addCriterion("idcard >=", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardLessThan(String value) {
		addCriterion("idcard <", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardLessThanOrEqualTo(String value) {
		addCriterion("idcard <=", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardLike(String value) {
		addCriterion("idcard like", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardNotLike(String value) {
		addCriterion("idcard not like", value, "idcard");
		return this;
	}
	
	public Criteria andIdcardIn(List values) {
		addCriterion("idcard in", values, "idcard");
		return this;
	}
	
	public Criteria andIdcardNotIn(List values) {
		addCriterion("idcard not in", values, "idcard");
		return this;
	}
	
	public Criteria andIdcardBetween(String value1, String value2) {
		addCriterion("idcard between", value1, value2, "idcard");
		return this;
	}
	
	public Criteria andIdcardNotBetween(String value1, String value2) {
		addCriterion("idcard not between", value1, value2, "idcard");
		return this;
	}
	
	public Criteria andAgeIsNull() {
		addCriterion("age is null");
		return this;
	}
	
	public Criteria andAgeIsNotNull() {
		addCriterion("age is not null");
		return this;
	}
	
	public Criteria andAgeEqualTo(String value) {
		addCriterion("age =", value, "age");
		return this;
	}
	
	public Criteria andAgeNotEqualTo(String value) {
		addCriterion("age <>", value, "age");
		return this;
	}
	
	public Criteria andAgeGreaterThan(String value) {
		addCriterion("age >", value, "age");
		return this;
	}
	
	public Criteria andAgeGreaterThanOrEqualTo(String value) {
		addCriterion("age >=", value, "age");
		return this;
	}
	
	public Criteria andAgeLessThan(String value) {
		addCriterion("age <", value, "age");
		return this;
	}
	
	public Criteria andAgeLessThanOrEqualTo(String value) {
		addCriterion("age <=", value, "age");
		return this;
	}
	
	public Criteria andAgeLike(String value) {
		addCriterion("age like", value, "age");
		return this;
	}
	
	public Criteria andAgeNotLike(String value) {
		addCriterion("age not like", value, "age");
		return this;
	}
	
	public Criteria andAgeIn(List values) {
		addCriterion("age in", values, "age");
		return this;
	}
	
	public Criteria andAgeNotIn(List values) {
		addCriterion("age not in", values, "age");
		return this;
	}
	
	public Criteria andAgeBetween(String value1, String value2) {
		addCriterion("age between", value1, value2, "age");
		return this;
	}
	
	public Criteria andAgeNotBetween(String value1, String value2) {
		addCriterion("age not between", value1, value2, "age");
		return this;
	}
	
	public Criteria andGenderIsNull() {
		addCriterion("gender is null");
		return this;
	}
	
	public Criteria andGenderIsNotNull() {
		addCriterion("gender is not null");
		return this;
	}
	
	public Criteria andGenderEqualTo(String value) {
		addCriterion("gender =", value, "gender");
		return this;
	}
	
	public Criteria andGenderNotEqualTo(String value) {
		addCriterion("gender <>", value, "gender");
		return this;
	}
	
	public Criteria andGenderGreaterThan(String value) {
		addCriterion("gender >", value, "gender");
		return this;
	}
	
	public Criteria andGenderGreaterThanOrEqualTo(String value) {
		addCriterion("gender >=", value, "gender");
		return this;
	}
	
	public Criteria andGenderLessThan(String value) {
		addCriterion("gender <", value, "gender");
		return this;
	}
	
	public Criteria andGenderLessThanOrEqualTo(String value) {
		addCriterion("gender <=", value, "gender");
		return this;
	}
	
	public Criteria andGenderLike(String value) {
		addCriterion("gender like", value, "gender");
		return this;
	}
	
	public Criteria andGenderNotLike(String value) {
		addCriterion("gender not like", value, "gender");
		return this;
	}
	
	public Criteria andGenderIn(List values) {
		addCriterion("gender in", values, "gender");
		return this;
	}
	
	public Criteria andGenderNotIn(List values) {
		addCriterion("gender not in", values, "gender");
		return this;
	}
	
	public Criteria andGenderBetween(String value1, String value2) {
		addCriterion("gender between", value1, value2, "gender");
		return this;
	}
	
	public Criteria andGenderNotBetween(String value1, String value2) {
		addCriterion("gender not between", value1, value2, "gender");
		return this;
	}
	
	public Criteria andArchIsNull() {
		addCriterion("arch is null");
		return this;
	}
	
	public Criteria andArchIsNotNull() {
		addCriterion("arch is not null");
		return this;
	}
	
	public Criteria andArchEqualTo(String value) {
		addCriterion("arch =", value, "arch");
		return this;
	}
	
	public Criteria andArchNotEqualTo(String value) {
		addCriterion("arch <>", value, "arch");
		return this;
	}
	
	public Criteria andArchGreaterThan(String value) {
		addCriterion("arch >", value, "arch");
		return this;
	}
	
	public Criteria andArchGreaterThanOrEqualTo(String value) {
		addCriterion("arch >=", value, "arch");
		return this;
	}
	
	public Criteria andArchLessThan(String value) {
		addCriterion("arch <", value, "arch");
		return this;
	}
	
	public Criteria andArchLessThanOrEqualTo(String value) {
		addCriterion("arch <=", value, "arch");
		return this;
	}
	
	public Criteria andArchLike(String value) {
		addCriterion("arch like", value, "arch");
		return this;
	}
	
	public Criteria andArchNotLike(String value) {
		addCriterion("arch not like", value, "arch");
		return this;
	}
	
	public Criteria andArchIn(List values) {
		addCriterion("arch in", values, "arch");
		return this;
	}
	
	public Criteria andArchNotIn(List values) {
		addCriterion("arch not in", values, "arch");
		return this;
	}
	
	public Criteria andArchBetween(String value1, String value2) {
		addCriterion("arch between", value1, value2, "arch");
		return this;
	}
	
	public Criteria andArchNotBetween(String value1, String value2) {
		addCriterion("arch not between", value1, value2, "arch");
		return this;
	}
	
	public Criteria andCreatetimeIsNull() {
		addCriterion("createtime is null");
		return this;
	}
	
	public Criteria andCreatetimeIsNotNull() {
		addCriterion("createtime is not null");
		return this;
	}
	
	public Criteria andCreatetimeEqualTo(String value) {
		addCriterion("createtime =", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotEqualTo(String value) {
		addCriterion("createtime <>", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeGreaterThan(String value) {
		addCriterion("createtime >", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
		addCriterion("createtime >=", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeLessThan(String value) {
		addCriterion("createtime <", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeLessThanOrEqualTo(String value) {
		addCriterion("createtime <=", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeLike(String value) {
		addCriterion("createtime like", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotLike(String value) {
		addCriterion("createtime not like", value, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeIn(List values) {
		addCriterion("createtime in", values, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotIn(List values) {
		addCriterion("createtime not in", values, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeBetween(String value1, String value2) {
		addCriterion("createtime between", value1, value2, "createtime");
		return this;
	}
	
	public Criteria andCreatetimeNotBetween(String value1, String value2) {
		addCriterion("createtime not between", value1, value2, "createtime");
		return this;
	}
	
	public Criteria andBirthIsNull() {
		addCriterion("birth is null");
		return this;
	}
	
	public Criteria andBirthIsNotNull() {
		addCriterion("birth is not null");
		return this;
	}
	
	public Criteria andBirthEqualTo(String value) {
		addCriterion("birth =", value, "birth");
		return this;
	}
	
	public Criteria andBirthNotEqualTo(String value) {
		addCriterion("birth <>", value, "birth");
		return this;
	}
	
	public Criteria andBirthGreaterThan(String value) {
		addCriterion("birth >", value, "birth");
		return this;
	}
	
	public Criteria andBirthGreaterThanOrEqualTo(String value) {
		addCriterion("birth >=", value, "birth");
		return this;
	}
	
	public Criteria andBirthLessThan(String value) {
		addCriterion("birth <", value, "birth");
		return this;
	}
	
	public Criteria andBirthLessThanOrEqualTo(String value) {
		addCriterion("birth <=", value, "birth");
		return this;
	}
	
	public Criteria andBirthLike(String value) {
		addCriterion("birth like", value, "birth");
		return this;
	}
	
	public Criteria andBirthNotLike(String value) {
		addCriterion("birth not like", value, "birth");
		return this;
	}
	
	public Criteria andBirthIn(List values) {
		addCriterion("birth in", values, "birth");
		return this;
	}
	
	public Criteria andBirthNotIn(List values) {
		addCriterion("birth not in", values, "birth");
		return this;
	}
	
	public Criteria andBirthBetween(String value1, String value2) {
		addCriterion("birth between", value1, value2, "birth");
		return this;
	}
	
	public Criteria andBirthNotBetween(String value1, String value2) {
		addCriterion("birth not between", value1, value2, "birth");
		return this;
	}
	
	public Criteria andPoweraIsNull() {
		addCriterion("powerA is null");
		return this;
	}
	
	public Criteria andPoweraIsNotNull() {
		addCriterion("powerA is not null");
		return this;
	}
	
	public Criteria andPoweraEqualTo(String value) {
		addCriterion("powerA =", value, "powera");
		return this;
	}
	
	public Criteria andPoweraNotEqualTo(String value) {
		addCriterion("powerA <>", value, "powera");
		return this;
	}
	
	public Criteria andPoweraGreaterThan(String value) {
		addCriterion("powerA >", value, "powera");
		return this;
	}
	
	public Criteria andPoweraGreaterThanOrEqualTo(String value) {
		addCriterion("powerA >=", value, "powera");
		return this;
	}
	
	public Criteria andPoweraLessThan(String value) {
		addCriterion("powerA <", value, "powera");
		return this;
	}
	
	public Criteria andPoweraLessThanOrEqualTo(String value) {
		addCriterion("powerA <=", value, "powera");
		return this;
	}
	
	public Criteria andPoweraLike(String value) {
		addCriterion("powerA like", value, "powera");
		return this;
	}
	
	public Criteria andPoweraNotLike(String value) {
		addCriterion("powerA not like", value, "powera");
		return this;
	}
	
	public Criteria andPoweraIn(List values) {
		addCriterion("powerA in", values, "powera");
		return this;
	}
	
	public Criteria andPoweraNotIn(List values) {
		addCriterion("powerA not in", values, "powera");
		return this;
	}
	
	public Criteria andPoweraBetween(String value1, String value2) {
		addCriterion("powerA between", value1, value2, "powera");
		return this;
	}
	
	public Criteria andPoweraNotBetween(String value1, String value2) {
		addCriterion("powerA not between", value1, value2, "powera");
		return this;
	}
	
	public Criteria andGainIsNull() {
		addCriterion("gain is null");
		return this;
	}
	
	public Criteria andGainIsNotNull() {
		addCriterion("gain is not null");
		return this;
	}
	
	public Criteria andGainEqualTo(String value) {
		addCriterion("gain =", value, "gain");
		return this;
	}
	
	public Criteria andGainNotEqualTo(String value) {
		addCriterion("gain <>", value, "gain");
		return this;
	}
	
	public Criteria andGainGreaterThan(String value) {
		addCriterion("gain >", value, "gain");
		return this;
	}
	
	public Criteria andGainGreaterThanOrEqualTo(String value) {
		addCriterion("gain >=", value, "gain");
		return this;
	}
	
	public Criteria andGainLessThan(String value) {
		addCriterion("gain <", value, "gain");
		return this;
	}
	
	public Criteria andGainLessThanOrEqualTo(String value) {
		addCriterion("gain <=", value, "gain");
		return this;
	}
	
	public Criteria andGainLike(String value) {
		addCriterion("gain like", value, "gain");
		return this;
	}
	
	public Criteria andGainNotLike(String value) {
		addCriterion("gain not like", value, "gain");
		return this;
	}
	
	public Criteria andGainIn(List values) {
		addCriterion("gain in", values, "gain");
		return this;
	}
	
	public Criteria andGainNotIn(List values) {
		addCriterion("gain not in", values, "gain");
		return this;
	}
	
	public Criteria andGainBetween(String value1, String value2) {
		addCriterion("gain between", value1, value2, "gain");
		return this;
	}
	
	public Criteria andGainNotBetween(String value1, String value2) {
		addCriterion("gain not between", value1, value2, "gain");
		return this;
	}
	}
}