package com.ciotc.teemo.domain;

public class Shortcomnts {
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shortcomnts.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shortcomnts.records
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private String records;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shortcomnts.id
	 * @return  the value of shortcomnts.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shortcomnts.id
	 * @param id  the value for shortcomnts.id
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shortcomnts.records
	 * @return  the value of shortcomnts.records
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public String getRecords() {
		return records;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shortcomnts.records
	 * @param records  the value for shortcomnts.records
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void setRecords(String records) {
		this.records = records;
	}

	public String toString(){
    		return records;
        }
}