package com.ciotc.teemo.menu;

import static com.ciotc.teemo.resource.MyResources.getResourceString;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.InputVerifier;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import org.apache.commons.configuration.PropertiesConfiguration;

import com.ciotc.teemo.usbdll.USBDLL;
import com.ciotc.teemo.util.GeneralUtils;

public class GainInputingDialog extends JDialog {
	/**
	    * Creates new form NewJDialog2
	    */
	public GainInputingDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		loadGainInformation();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField(5);
		jTextField3 = new javax.swing.JTextField(5);
		jTextField5 = new javax.swing.JTextField(5);
		jTextField7 = new javax.swing.JTextField(5);
		jTextField9 = new javax.swing.JTextField(5);
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		ok = new javax.swing.JButton();
		cancel = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		defaultButton = new javax.swing.JButton();
		
	        jComboBox1 = new javax.swing.JComboBox();
	        jComboBox2 = new javax.swing.JComboBox();
	        jComboBox3 = new javax.swing.JComboBox();
	        jComboBox4 = new javax.swing.JComboBox();
	        jComboBox5 = new javax.swing.JComboBox();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText(getResourceString("gainSettingDialog.bordertitle") + "1");

		jLabel2.setText(getResourceString("gainSettingDialog.bordertitle") + "2");

		jLabel3.setText(getResourceString("gainSettingDialog.bordertitle") + "3");

		jLabel4.setText(getResourceString("gainSettingDialog.bordertitle") + "4");

		jLabel5.setText(getResourceString("gainSettingDialog.bordertitle") + "5");

		jLabel6.setText(getResourceString("gainSettingDialog.powA"));

		jLabel7.setText(getResourceString("gainSettingDialog.gain"));

//		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "5", "8", "10", "16","32" }));

//		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "5", "8", "10", "16","32" }));

//		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "5", "8", "10", "16","32" }));

//		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "5", "8", "10", "16","32" }));

//		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "5", "8", "10", "16","32" }));
		
		
		setTextByGainVaule();

		ok.setText(getResourceString("ok"));

		ok.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				//保存数据到文件
				getTextByGainVaule();
				saveGainInformation();
				//setVisible(false);
				dispose();
			}

		});

		cancel.setText(getResourceString("cancel"));

		cancel.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				//不做任何保存
				//setVisible(false);
				dispose();
			}
		});

		jLabel13.setText(getResourceString("gainSettingDialog.value"));

		defaultButton.setText(getResourceString("default"));

		defaultButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				//还原原来的值
				restoreGainInformation();
				setTextByGainVaule();

			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(0, 20, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
	                            .addComponent(jLabel5)
	                            .addComponent(jLabel1)
	                            .addComponent(jLabel4)
	                            .addComponent(jLabel2)
	                            .addComponent(jLabel3))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING))
	                            .addComponent(jLabel6))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel7))
	                        .addGap(18, 18, 18)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel8)
	                            .addComponent(jLabel9)
	                            .addComponent(jLabel10)
	                            .addComponent(jLabel12)
	                            .addComponent(jLabel11)
	                            .addComponent(jLabel13)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(ok)
	                        .addGap(5, 5, 5)
	                        .addComponent(cancel)
	                        .addGap(2, 2, 2)
	                        .addComponent(defaultButton)))
	                .addGap(11, 11, 11))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(23, 23, 23)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel7)
	                    .addComponent(jLabel13)
	                    .addComponent(jLabel6))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel1)
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel8))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2)
	                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel9)
	                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3)
	                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel10)
	                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4)
	                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel11)
	                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel5)
	                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel12)
	                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(10, 10, 10)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(defaultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addContainerGap())
	        );
	        
		addInputVerifer();
		addItemListener();
		
		pack();
		setTitle(getResourceString("gainInputtingDialog.title"));
		setAlwaysOnTop(true);
		setLocationRelativeTo(null);
		setResizable(false);
		setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		
	}

	private void addItemListener(){
		MyItemListener mil = new MyItemListener();
		jComboBox1.addItemListener(mil);jComboBox1.setName("jcb1");
		jComboBox2.addItemListener(mil);jComboBox2.setName("jcb2");
		jComboBox3.addItemListener(mil);jComboBox3.setName("jcb3");
		jComboBox4.addItemListener(mil);jComboBox4.setName("jcb4");
		jComboBox5.addItemListener(mil);jComboBox5.setName("jcb5");
	}
	
	private void addInputVerifer(){
		MyInputVerifier miv = new MyInputVerifier();
		jTextField1.setInputVerifier(miv);jTextField1.setName("jtf1");
		jTextField3.setInputVerifier(miv);jTextField3.setName("jtf3");
		jTextField5.setInputVerifier(miv);jTextField5.setName("jtf5");
		jTextField7.setInputVerifier(miv);jTextField7.setName("jtf7");
		jTextField9.setInputVerifier(miv);jTextField9.setName("jtf9");
	}
	
	final static int maxVal = 200; 
	
	class MyItemListener implements ItemListener{

		@SuppressWarnings("rawtypes")
		@Override
		public void itemStateChanged(ItemEvent e) {
			JComboBox jcb = (JComboBox) e.getSource();
			if(e.getStateChange() == ItemEvent.DESELECTED) return;
			if(jcb.getName().equals("jcb1")){
				int in = Integer.parseInt(jTextField1.getText());
				int val = Integer.parseInt((String)e.getItem()) * in;
				jLabel8.setText(val+"");
				if(val >= maxVal || val <=0 ){
					showTipInformation(0,maxVal);
					jComboBox1.setSelectedIndex(gains[0]); //还原
					return ;
				}
				gains[0] = jcb.getSelectedIndex();//Integer.parseInt((String)e.getItem());
			}else if(jcb.getName().equals("jcb2")){
				int in = Integer.parseInt(jTextField3.getText());
				int val = Integer.parseInt((String)e.getItem()) * in;
				jLabel9.setText(val+"");
				if(val >= maxVal || val <=0 ){
					showTipInformation(0,maxVal);
					jComboBox2.setSelectedIndex(gains[1]); //还原
					return ;
				}
				gains[1] = jcb.getSelectedIndex();//Integer.parseInt((String)e.getItem());
			}else if(jcb.getName().equals("jcb3")){
				int in = Integer.parseInt(jTextField5.getText());
				int val = Integer.parseInt((String)e.getItem()) * in;
				jLabel10.setText(val+"");
				if(val >= maxVal || val <=0 ){
					showTipInformation(0,maxVal);
					jComboBox3.setSelectedIndex(gains[2]); //还原
					return ;
				}
				gains[2] = jcb.getSelectedIndex();//Integer.parseInt((String)e.getItem());
			}else if(jcb.getName().equals("jcb4")){
				int in = Integer.parseInt(jTextField7.getText());
				int val = Integer.parseInt((String)e.getItem()) * in;
				jLabel11.setText(val+"");
				if(val >= maxVal || val <=0 ){
					showTipInformation(0,maxVal);
					jComboBox4.setSelectedIndex(gains[3]); //还原
					return ;
				}
				gains[3] = jcb.getSelectedIndex();//Integer.parseInt((String)e.getItem());
			}else if(jcb.getName().equals("jcb5")){
				int in = Integer.parseInt(jTextField9.getText());
				int val = Integer.parseInt((String)e.getItem()) * in;
				jLabel12.setText(val+"");
				if(val >= maxVal || val <=0 ){
					showTipInformation(0,maxVal);
					jComboBox5.setSelectedIndex(gains[4]); //还原
					return ;
				}
				gains[4] = jcb.getSelectedIndex();//Integer.parseInt((String)e.getItem());
			}
		}
		
	}
	
	class MyInputVerifier extends InputVerifier {

		@Override
		public boolean verify(JComponent input) {
			JTextField jtf = (JTextField) input;
			try {
				int in = Integer.parseInt(jtf.getText());
				int val  = 0;
				if(jtf.getName().equals("jtf1")){
					val = in*USBDLL.GAINS[jComboBox1.getSelectedIndex()];
					jLabel8.setText(val+"");
				} else if(jtf.getName().equals("jtf3")){
					val = in*USBDLL.GAINS[jComboBox2.getSelectedIndex()];
					jLabel9.setText(val+"");
				}else if(jtf.getName().equals("jtf5")){
					val = in*USBDLL.GAINS[jComboBox3.getSelectedIndex()];
					jLabel10.setText(val+"");
				}else if(jtf.getName().equals("jtf7")){
					val = in*USBDLL.GAINS[jComboBox4.getSelectedIndex()];
					jLabel11.setText(val+"");
				}else if(jtf.getName().equals("jtf9")){
					val = in*USBDLL.GAINS[jComboBox5.getSelectedIndex()];
					jLabel12.setText(val+"");
				}
				if(val >= maxVal || val <=0 ){
					showTipInformation(0,maxVal);
					return false;
				}
			} catch (Exception e) {
				showTipInformation();
				return false;
			}
			return true;
		}

	}

	/**
	 * 提示输入的数据不在最大和最小范围之内
	 * 
	 * @param maxValue
	 *                最大值
	 * @param minValue
	 *                最小值
	 */
	private void showTipInformation(int minValue, int maxValue) {
		JOptionPane.showMessageDialog(this, getResourceString("tipforErrorInputing2") + "  " + minValue + "~" + maxValue, getResourceString("Teemo"), JOptionPane.ERROR_MESSAGE);
	}
	
	/**
	 * 提示输入的数据格式不正确
	 */
	private void showTipInformation() {
		JOptionPane.showMessageDialog(this, getResourceString("tipforErrorInputing"), getResourceString("Teemo"), JOptionPane.ERROR_MESSAGE);
	}
	
	/**
	 * 根据pwas和gains两个数组的值设置文本
	 */
	private void setTextByGainVaule() {
		jTextField1.setText(pwas[0]);
		jComboBox1.setSelectedIndex(gains[0]);

		jTextField3.setText(pwas[1]);
		jComboBox2.setSelectedIndex(gains[1]);

		jTextField5.setText(pwas[2]);
		jComboBox3.setSelectedIndex(gains[2]);

		jTextField7.setText(pwas[3]);
		jComboBox4.setSelectedIndex(gains[3]);

		jTextField9.setText(pwas[4]);
		jComboBox5.setSelectedIndex(gains[4]);

		String[] vals = new String[size];
		for (int i = 0; i < size; i++) {
			int tt = Integer.parseInt(pwas[i]) * USBDLL.GAINS[gains[i]];
			vals[i] = String.valueOf(tt);
		}

		jLabel8.setText(vals[0]);

		jLabel9.setText(vals[1]);

		jLabel10.setText(vals[2]);

		jLabel11.setText(vals[3]);

		jLabel12.setText(vals[4]);
	}

	/**
	 * 根据文本的值来设置那两个数组
	 */
	private void getTextByGainVaule() {
		pwas[0] = jTextField1.getText();
		gains[0] = jComboBox1.getSelectedIndex();

		pwas[1] = jTextField3.getText();
		gains[1] = jComboBox2.getSelectedIndex();

		pwas[2] = jTextField5.getText();
		gains[2] = jComboBox3.getSelectedIndex();

		pwas[3] = jTextField7.getText();
		gains[3] = jComboBox4.getSelectedIndex();

		pwas[4] = jTextField9.getText();
		gains[4] = jComboBox5.getSelectedIndex();
	}

	int size = 5;
	String[] pwas = new String[size];
	Integer[] gains = new Integer[size];
	PropertiesConfiguration pc = GeneralUtils.getProp();

	/**
	 * 加载所有的增益值
	 */
	private void loadGainInformation() {

		for (int i = 0; i < size; i++) {
			pwas[i] = (String) pc.getProperty("pwa" + (i + 1));
			gains[i] = Integer.parseInt((String) pc.getProperty("gain" + (i + 1)));
		}
	}

	/**
	 * 保存所有的增益值
	 */
	private void saveGainInformation() {
		for (int i = 0; i < size; i++) {
			pc.setProperty("pwa" + (i + 1), pwas[i]);
			pc.setProperty("gain" + (i + 1), String.valueOf(gains[i]));
		}
	}

	/**
	 * 还原所有的增益值
	 * 默认的值需最后再定
	 */
	private void restoreGainInformation() {
		//默认值
		String[] pwas0 = { "6", "8", "10", "18", "20" };
		Integer[] gains0 = { 0, 0, 0, 0, 0 };
		for (int i = 0; i < size; i++) {
			pwas[i] = pwas0[i];
			gains[i] = gains0[i];
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				GainInputingDialog dialog = new GainInputingDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
				dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton cancel;
	private javax.swing.JButton defaultButton;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox1;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox2;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox3;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox4;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField9;
	private javax.swing.JButton ok;
	// End of variables declaration
}
