package com.ciotc.teemo.menu;

import static com.ciotc.teemo.resource.MyResources.getResourceString;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.prefs.Preferences;

import javax.swing.JDialog;

import org.apache.commons.configuration.PropertiesConfiguration;

import com.ciotc.teemo.frame.MainFrame;
import com.ciotc.teemo.util.GeneralUtils;
public class GainSettingDialog extends JDialog {
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton cancel;
	private javax.swing.JButton defaultButton;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JButton ok;
	private javax.swing.JButton setting;

	PropertiesConfiguration pc = GeneralUtils.getProp();
	int selection = 3;
	
	/**
	 * Creates new form NewJDialog1
	 */
	public GainSettingDialog() {
		setModal(true);
		loadGainSelectionInformation();
		initComponents();
	}
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		
		buttonGroup1.add(jRadioButton1);
		buttonGroup1.add(jRadioButton2);
		buttonGroup1.add(jRadioButton3);
		buttonGroup1.add(jRadioButton4);
		buttonGroup1.add(jRadioButton5);
		
		setRadioButtonBySelection();
		
		ok = new javax.swing.JButton();
		cancel = new javax.swing.JButton();
		setting = new javax.swing.JButton();
		defaultButton = new javax.swing.JButton();
		

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(getResourceString("gainSettingDialog.bordertitle")));

		jRadioButton1.setText(getResourceString("gainSettingDialog.bordertitle")+"1");

		jRadioButton2.setText(getResourceString("gainSettingDialog.bordertitle")+"2");

		jRadioButton3.setText(getResourceString("gainSettingDialog.bordertitle")+"3"+"("+getResourceString("default")+")");

		jRadioButton4.setText(getResourceString("gainSettingDialog.bordertitle")+"4");

		jRadioButton5.setText(getResourceString("gainSettingDialog.bordertitle")+"5");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jRadioButton1).addComponent(jRadioButton2).addComponent(jRadioButton3).addComponent(jRadioButton4).addComponent(jRadioButton5))
						.addContainerGap(24, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jRadioButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jRadioButton3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton4).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton5)
						.addContainerGap(17, Short.MAX_VALUE)));

		ok.setText(getResourceString("ok"));
		
		ok.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				//保存修改的值
				saveGainSelectionInformation();
				saveGainInformation();
				//setVisible(false);
				dispose();
			}
		});

		cancel.setText(getResourceString("cancel"));
		
		cancel.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				//将值还原
				loadGainSelectionInformation();
				setRadioButtonBySelection();
				//setVisible(false);
				dispose();
			}
		});

		defaultButton.setText(getResourceString("default"));

		defaultButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				setDefaultSelction();
			}
		});
		
		setting.setText(getResourceString("setting"));

		setting.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				//进行设置
				GainInputingDialog gid = new GainInputingDialog(null,true);
				gid.setVisible(true);
			}
		});
		
		 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		        getContentPane().setLayout(layout);
		        layout.setHorizontalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addContainerGap()
		                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(ok)
		                    .addComponent(cancel)
		                    .addComponent(defaultButton)
		                    .addComponent(setting))
		                .addGap(19, 19, 19))
		        );
		        layout.setVerticalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addGroup(layout.createSequentialGroup()
		                        .addGap(40, 40, 40)
		                        .addComponent(ok)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addComponent(cancel)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addComponent(defaultButton)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addComponent(setting)
		                        .addGap(0, 0, Short.MAX_VALUE))
		                    .addGroup(layout.createSequentialGroup()
		                        .addGap(28, 28, 28)
		                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		                .addContainerGap())
		        );
		       
		addActionListener();        
		
		pack();
		setTitle(getResourceString("gainSettingDialog.title"));
		//setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
		setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		setAlwaysOnTop(true);
		setLocationRelativeTo(null);
		setResizable(false);
	}


	public void setRadioButtonBySelection() {
		switch(selection){
		case 1:
			jRadioButton1.setSelected(true);
			break;
		case 2:
			jRadioButton2.setSelected(true);
			break;
		case 3:
			jRadioButton3.setSelected(true);
			break;
		case 4:
			jRadioButton4.setSelected(true);
			break;
		case 5:
			jRadioButton5.setSelected(true);
			break;
		default:
			jRadioButton3.setSelected(true); //默认的选择第三个
			break;
		}
	}
	
	/**
	 * 选择哪一个增益值 它从user.properties中读取
	 */
	public void loadGainSelectionInformation() {
		 selection =  Integer.parseInt((String) pc.getProperty("gainselection"));
	}
	
	/**
	 * 将所作的选择保存回user.properties
	 */
	private void saveGainSelectionInformation() {
		pc.setProperty("gainselection", String.valueOf(selection));
	}
	
	/**
	 * 根据selction 得到powa和gain值 并将它们保存到Prefreneces中去
	 */
	private void saveGainInformation(){
		Preferences pref = Preferences.userNodeForPackage(MainFrame.class);
		int powa = 10 ;
		int gain = 4;
		switch(selection){
		case 1:
			powa = Integer.parseInt((String)pc.getProperty("pwa1"));
			gain = Integer.parseInt((String)pc.getProperty("gain1"));
			break;
		case 2:
			powa = Integer.parseInt((String)pc.getProperty("pwa2"));
			gain = Integer.parseInt((String)pc.getProperty("gain2"));
			break;
		case 3:
			powa = Integer.parseInt((String)pc.getProperty("pwa3"));
			gain = Integer.parseInt((String)pc.getProperty("gain3"));
			break;
		case 4:
			powa = Integer.parseInt((String)pc.getProperty("pwa4"));
			gain = Integer.parseInt((String)pc.getProperty("gain4"));
			break;
		case 5:
			powa = Integer.parseInt((String)pc.getProperty("pwa5"));
			gain = Integer.parseInt((String)pc.getProperty("gain5"));
			break;
		default:
			break;
		}
		pref.putInt("powa", powa);
		pref.putInt("gain",gain);
	}
	
	/**
	 * 设置默认选择 默认是第三个被选中
	 */
	private void setDefaultSelction(){
		selection = 3;
		jRadioButton3.setSelected(true);
	}
	
	private void addActionListener(){
		MyActionListener mal = new MyActionListener();
		jRadioButton1.addActionListener(mal);jRadioButton1.setActionCommand("jrb1");
		jRadioButton2.addActionListener(mal);jRadioButton2.setActionCommand("jrb2");
		jRadioButton3.addActionListener(mal);jRadioButton3.setActionCommand("jrb3");
		jRadioButton4.addActionListener(mal);jRadioButton4.setActionCommand("jrb4");
		jRadioButton5.addActionListener(mal);jRadioButton5.setActionCommand("jrb5");
	}
	
	class MyActionListener implements ActionListener{

		@Override
		public void actionPerformed(ActionEvent e) {
			if(e.getActionCommand().equals("jrb1")){
				selection = 1;
			}else if(e.getActionCommand().equals("jrb2")){
				selection = 2;
			}else if(e.getActionCommand().equals("jrb3")){
				selection = 3;
			}else if(e.getActionCommand().equals("jrb4")){
				selection = 4;
			}else if(e.getActionCommand().equals("jrb5")){
				selection = 5;
			} 
		}
		
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				GainSettingDialog dialog = new GainSettingDialog();
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
				dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
			}
		});
	}
}
