package com.ciotc.teemo.dao;

import com.ciotc.teemo.domain.Movies;
import com.ciotc.teemo.domain.MoviesExample;
import java.sql.SQLException;
import java.util.List;

public interface MoviesDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int countByExample(MoviesExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int deleteByExample(MoviesExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int deleteByPrimaryKey(String id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	void insert(Movies record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	void insertSelective(Movies record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	List selectByExample(MoviesExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	Movies selectByPrimaryKey(String id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int updateByExampleSelective(Movies record, MoviesExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int updateByExample(Movies record, MoviesExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int updateByPrimaryKeySelective(Movies record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movies
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	int updateByPrimaryKey(Movies record) throws SQLException;
}