package com.ciotc.teemo.dao;

import com.ciotc.teemo.domain.Shortcomnts;
import com.ciotc.teemo.domain.ShortcomntsExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class ShortcomntsDAOImpl implements ShortcomntsDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public ShortcomntsDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int countByExample(ShortcomntsExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"shortcomnts.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int deleteByExample(ShortcomntsExample example) throws SQLException {
		int rows = sqlMapClient.delete("shortcomnts.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int deleteByPrimaryKey(String id) throws SQLException {
		Shortcomnts key = new Shortcomnts();
		key.setId(id);
		int rows = sqlMapClient.delete("shortcomnts.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void insert(Shortcomnts record) throws SQLException {
		sqlMapClient.insert("shortcomnts.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public void insertSelective(Shortcomnts record) throws SQLException {
		sqlMapClient.insert("shortcomnts.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public List selectByExample(ShortcomntsExample example) throws SQLException {
		List list = sqlMapClient.queryForList("shortcomnts.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public Shortcomnts selectByPrimaryKey(String id) throws SQLException {
		Shortcomnts key = new Shortcomnts();
		key.setId(id);
		Shortcomnts record = (Shortcomnts) sqlMapClient.queryForObject(
				"shortcomnts.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int updateByExampleSelective(Shortcomnts record, ShortcomntsExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("shortcomnts.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int updateByExample(Shortcomnts record, ShortcomntsExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("shortcomnts.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int updateByPrimaryKeySelective(Shortcomnts record) throws SQLException {
		int rows = sqlMapClient.update("shortcomnts.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	public int updateByPrimaryKey(Shortcomnts record) throws SQLException {
		int rows = sqlMapClient.update("shortcomnts.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table shortcomnts
	 * @ibatorgenerated  Mon Apr 16 15:06:52 CST 2012
	 */
	private static class UpdateByExampleParms extends ShortcomntsExample {
	private Object record;
	
	public UpdateByExampleParms(Object record, ShortcomntsExample example) {
		super(example);
		this.record = record;
	}
	
	public Object getRecord() {
		return record;
	}
	}
}